### ISSUE TITLE
Tracking issue for Incrementally Updated Materialized Views

### ISSUE THREAD

**Issue by arjunravinarayan** [arjunravinarayan/cockroach#11]
Dependency 1
- [x] Start RFC for on-disk storage: cockroachdb/cockroach#16069
- [x] Merge RFC for on-disk storage
- [x] Implement on-disk storage (1.1): cockroachdb/cockroach#16716

Dependency 2
- [x] RFCs for changefeeds: single node change feeds (Toby): cockroachdb/cockroach#16838
- [x] RFCs for changefeeds: CDC spec and spec DistSQL processor for merging multi-range change feeds into a single change feed
- [ ] Merge all RFCs for changefeeds
- [ ] Implement change feeds part 1: single node change feeds (Toby) (1.2)
- [ ] Implement change feeds part 2: DistSQL processor for merging multi-range change feeds

Dependency 3
- [ ] Start RFC for fault tolerant DistSQL subgraphs
- [ ] Merge RFC for fault tolerant DistSQL subgraphs
- [ ] Implement fault tolerant DistSQL subgraphs

Dependency 4
- [ ] Implement fine-grained latency tracking for DistSQL processors
- [ ] Use that to generate some performance reports on existing TPC-H queries

Phase 1: MVP
- [ ] Implement Timelystamp propagation throughout
- [ ] Benchmark the overhead of passing Timelystamps everywhere
- [ ] Add a single example Differential Dataflow processor 

Phase 2: Materialized Views Public Alpha
- [x] Start RFC for Incrementally Updated Materialized Views: [draft RFC](https://github.com/arjunravinarayan/materializedviews/blob/master/materialized_views.md)
- [ ] Spec out a few Differential Dataflow processors (linear operators, joins and groupbys first?)
- [ ] Merge RFC for Incrementally Updated Materialized Views

Phase 3: Materialized Views 1.0
- [ ] Write out additional Differential Dataflow processors
- [ ] Load test materialized views for TPC-H Scalefactor-1, under concurrent TPC-C load.

Phase 4: Post 1.0 tasks
- [ ] Zone configs for separate OLAP-Cockroach nodes vs OLTP-Cockroach nodes.
- [ ] Load test materialized views for TPC-H Scalefactor-30 under concurrent TPC-C load under chaos.

Phase 5: Pie in the sky future
- [ ] Investigate manually chaining multiple materialized views
- [ ] Investigate deduplication/shared processors between multiple materialized views.
- [ ] New benchmarks are needed for true HTAP systems, beyond just TPCC+TPCH. Investigate and begin designing better benchmarks.

**Comment by arjunravinarayan** [comment]
Closing this issue, and superceding it with a new one.
