### ISSUE TITLE
Checklist for external storage

### ISSUE THREAD

**Issue by arjunravinarayan** [arjunravinarayan/cockroach#13]
- [x] Pass all unit tests for all 3 commits, not just our PR. There are some interlocking moving parts. Don't dump those on Alfonso alone.
- [x] Run a test query on Navy that tests external storage: `SELECT count(*) FROM (SELECT * FROM tpch.lineitem ORDER BY l_orderkey, l_partkey, l_suppkey, l_linenumber, l_quantity, l_extendedprice, l_discount, l_tax, l_returnflag, l_linestatus, l_shipdate, l_commitdate, l_receiptdate, l_shipinstruct, l_shipmode, l_comment);`
- [x] Test multiple queries in flight at the same time.
- [x] Make sure it runs in series as well
- [x] Make sure that query OOMs naturally when external storage is disabled, as well, or use a better query.
- [x] Address final nits
- [x] Merge the PR and make sure Alfonso rebases on top of the merge. Make sure Alfonso is in sync with which changes he needs to make to his PR. Pair program these changes in to ensure no miscommunications.
