### ISSUE TITLE
perf: tracking issue for YCSB benchmarking

### ISSUE THREAD

**Issue by arjunravinarayan** [arjunravinarayan/cockroach#16]
- [ ] Run YCSB on denim on cockroach
- [ ] Run YCSB on denim on mongo
- [ ] Run YCSB on denim on cassandra
- [ ] Run YCSB on denim on postgres
- [ ] Run YCSB on denim on mysql
- [ ] On YCSB, are we read limited or write limited?
- [ ] Are we at 100% CPU when running YCSB?
- [ ] What's scalability like from 3-6 nodes?

**Comment by arjunravinarayan** [comment]
Out of the box YCSB on cockroach on a 6 node azure `d3_v2` cluster is 45k QPS.
Service latencies: 90%: 50ms, 99%: 120ms
Execution latencies: 90%: <1ms, 99%: 30ms

**Comment by vijay03** [comment]
Which workload are you looking at? Workload E?

**Comment by arjunravinarayan** [comment]
Workload B. This is a separate thread, unrelated to #15. Trying to find some low hanging fruit in CockroachDB, as we're not close to max performance.

**Comment by arjunravinarayan** [comment]
(I apologize if you're getting spammed - this is a fairly high volume repo because I write notes to myself here. I can explicitly ping you when I make progress on #15. If you set your email to only ping you on @ mentions, that might be better)
