### ISSUE TITLE
distsql: tracking issue for external storage load testing

### ISSUE THREAD

**Issue by arjunravinarayan** [arjunravinarayan/cockroach#17]
- [x] run TPC-H scalefactor 1 on `navy` with external storage threshold set low. verify its triggering in logs.
- [ ] run TPC-H scalefactor 5 on `navy` with default threshold.
- [ ] run `photos` with threshold set low.
- [ ] Find a configuration of the thresholds that we can then use to `photos` regularly on nightlies so that we are testing external storage in the long term.

**Comment by arjunravinarayan** [comment]
Since this isn't merged yet, but we want some preliminary load testing in time for tomorrow's team meeting, using unmerged SHA `4cfc1391c00ca87bd7c0835f8ca1ab4eb6e5e228` for all testing.

**Comment by arjunravinarayan** [comment]
Deploying to `navy` is blocked on the fact that photos aborted running analytics queries sometime this morning (started ~saturday), and I'm investigating using the existing cluster.

**Comment by arjunravinarayan** [comment]
it appears that the newly added query 4 from (cockroachdb/examples-go#109) is taking inordinately long to run due to an inefficient JOIN query plan, and will probably error out (and the load generator is probably not restarting the analytics worker correctly). I'm trying to repro (it's taking its time... 18 minutes and counting) before filing an issue and PR against the main repo.
